### ISSUE TITLE
konwersja na gem-a

### ISSUE THREAD

**Issue by 0xtrzy** [bbkr/HomoGlypher#5]
Co myślisz o zamiania ne gem-a? 
Ruby

**Comment by bbkr** [comment]
Nie czuje sie na tyle silny w Ruby, zeby napisac i utrzymywac gem z funkcjonalnoscia 1:1. Na przyklad w ogole nie wiem, czy tam mozna robic takie sztuczki z regexpami jak w Raku. Ruby ma swoja wlasna biblioteke do regexpow, to nawet nie jest PCRE ktore znam z Perla 5.

Ale nie widze problemu, zeby na przyklad wydzielic mappingi do bezkontekstowego repo. Wtedy jak znajdzie sie smialek do portowania na inny jezyk to bedzie mial gotowy zestaw glyphow do uzycia.

**Comment by bbkr** [comment]
Zamykam temat z powodow opisanych powyzej.

Jezeli ktos chce portowac to na Ruby to zapraszam do skorzystania z bazy glyphow.
Natomiast ja sam sie nie podejmuje takiej pracy.
